### ISSUE TITLE
The 4 tests failed executing $ make installcheck

### ISSUE THREAD

**Issue by aajimenezqs** [CartoDB/pg_schema_triggers#1]
I am try pass the test executing $ make installcheck, but this is the output:

/usr/lib/postgresql/9.3/lib/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=./ --psqldir='/usr/lib/postgresql/9.3/bin'    --dbname=contrib_regression event_trigger relation column trigger
(using postmaster on Unix socket, default port)
============== dropping database "contrib_regression" ==============
DROP DATABASE
============== creating database "contrib_regression" ==============
CREATE DATABASE
ALTER DATABASE
============== running regression test queries        ==============
test event_trigger            ... FAILED
test relation                 ... FAILED
test column                   ... FAILED
test trigger                  ... FAILED
# 

 4 of 4 tests failed. 

The differences that caused some tests to fail can be viewed in the
file "/home/aajimenezqs/Quarksoft/UEAF/CartoDB/pg_schema_triggers/regression.diffs".  A copy of the test summary that you see
above is saved in the file "/home/aajimenezqs/Quarksoft/UEAF/CartoDB/pg_schema_triggers/regression.out".

make: **\* [installcheck] Error 1

I add  the next line to /etc/postgresql/9.3/main/postgresql.conf: 
     shared_preload_libraries = 'schema_triggers.so'         # (change requires restart)

Then I reset the postgres service.

But the tests fails again.

What should I do?

Note: I review the next link yet: https://bitbucket.org/malloclabs/pg_schema_triggers/issue/7/processutility-hook-is-already-installed, but is another error.

Thanks in advance!

**Comment by aendra-rininsland** [comment]
+1, same boat here.

**Comment by ghost** [comment]
Same here, with a small correction. It only fails for test relation:

```
test relation ... FAILED
```

**Comment by pramsey** [comment]
Yeah, the relation test for some reason included a test that (a) created a custom schema and (b) reported out the oid of that schema. I can't imagine it worked more than once for the author. I've just removed it for now.
