### ISSUE TITLE
SnapshotNow was removed

### ISSUE THREAD

**Issue by ghost** [CartoDB/pg_schema_triggers#2]
SnapshotNow was removed from the Postgres codebase in August 2013.
http://www.postgresql.org/message-id/E1V4uGr-0006GY-DR@gemulon.postgresql.org

This stops pg_schema_triggers (and CartoDB) being used with anything over 9.3.6 (barring other maintenance releases in the 9.3.x series)

Is there a plan to upgrade the extension?

**Comment by javisantana** [comment]
I think the short term plan is to remove the dependency with this extension, we are not using it.

cc @pramsey

**Comment by pramsey** [comment]
Remove the dependency on SnapshotNow from the extension, or remove the dependency on the extension from CartoDB?

**Comment by javisantana** [comment]
> remove the dependency on the extension from CartoDB

that's it, we are not actually using it

**Comment by pramsey** [comment]
Given the future utility (allowing DDL by users without breaking cartodb), should I consider fixing the extension?

**Comment by javisantana** [comment]
yep, fixing the extension would be good but removing it for the moment would solve lot of problems. I don't know if postgres is planning to support this builtin.

Could you take a look?

**Comment by pramsey** [comment]
There's no real enhancement to event triggers in 9.4, so we'll need the extension there for sure. 9.5 may have some improvements, have to look more closely into it.

**Comment by ghost** [comment]
Some more background - I'm currently trying to build & run CartoDB on
Windows. Less extensions to build would be a good thing - should I skip
this one?

**Comment by javisantana** [comment]
@voltagex you can skip this extension for sure. 

You are brave :)

**Comment by pramsey** [comment]
The current master should be supported by 9.4 and I see no changes in 9.3 that remove SnapshotNow
